### ISSUE TITLE
Removed from BiocManager

### ISSUE THREAD

**Issue by Stortebecker** [thomasp85/MSGFplus#21]
With the newest version of BiocManager (v3.15), MSGFplus has been removed. If possible, I would like to avoid installing the package from Github, because I do not want to install Rtools on every computer where I use the package. 

Will there be an alternative way to install the package, either CRAN or BioConductor or a .tar.gz release?

**Comment by lgatto** [comment]
Yes, `MSGFplus` has been deprecated and isn't available in Bioconductor version 3.15 (and later). 

Are you sure you need Rtools to install the package? I don't think so (but there might be other issues with the package). Otherwise, you could build your own binaries with https://win-builder.r-project.org/ or fork the package and set up your own R-univers (https://r-universe.dev/search/) that will generate binaries for you.

**Comment by Stortebecker** [comment]
I solved the problem by building the package on one computer and distributing the .tar.gz. Maybe you could add tar.gz files as "Releases" for future updates?
